spring:
  kafka:
    bootstrap-servers: 10.105.23.11:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: lab:com.pactpharma.poc.model.Lab1,clinical:com.pactpharma.poc.model.Clinical1
